name: Catalog Service

on:
  push:
    paths:
      - 'Catalog-Service/**'
    branches:
      - 'master'
      - 'main'
  pull_request:
    paths:
      - 'Catalog-Service/**'
    branches:
      - 'master'
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # We define the working directory here so all steps
    # run inside the Catalog-Service folder
    defaults:
      run:
        working-directory: ./Catalog-Service

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        # -ntp stands for 'no-transfer-progress' to keep logs clean
        run: chmod +x mvnw && ./mvnw -ntp verify